sudo: false

language: node_js

node_js:
  - node
  - 4
  - 5
  - 6

env:
  global:
    - NODE_ENV=dev

matrix:
  allow_failures:
    - node_js: 4

cache:
  directories:
    - node_modules

before_script:
  - npm install -g npm
  - npm install -g gulp

script:
  - gulp build
  - npm test

#after_script:
#  - if [ $SENDCOVERAGE ]; then ./tools/coverage-calc.sh; ./tools/coverage-send.sh && rm -rf ./coverage; fi
