sudo: false

language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

#after_script:
#  - if [ $SENDCOVERAGE ]; then ./tools/coverage-calc.sh; ./tools/coverage-send.sh && rm -rf ./coverage; fi
