sudo: false

language: node_js

node_js:
  - stable
  - 4
  - 6

env:
  global:
    - NODE_ENV=dev

cache:
  directories:
    - node_modules

before_script:
  - npm install -g npm
  - npm install -g gulp

script:
  - gulp build

#after_script:
#  - if [ $SENDCOVERAGE ]; then ./tools/coverage-calc.sh; ./tools/coverage-send.sh && rm -rf ./coverage; fi
