sudo: false

language: node_js

node_js:
  - 5
  - stable

matrix:
  include:
    - node_js: stable
#      env: SENDCOVERAGE=1

cache:
  directories:
    - node_modules

#after_script:
#  - if [ $SENDCOVERAGE ]; then ./tools/coverage-calc.sh; ./tools/coverage-send.sh && rm -rf ./coverage; fi
