version: 0.4.1.{build}-{branch}

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

hosts:
  localhost: 127.0.0.1

# What combinations to test
environment:
  NODE_ENV: dev
  DEBUG: tndr*
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

platform:
#  - x86
  - x64

matrix:
  allow_failures:
    - nodejs_version: "4"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  # install modules
  - npm install
  - npm install -g gulp

before_test:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - gulp build

# Post-install test scripts.
test_script:
  # run tests
  - npm test

# Don't actually run MSBUILD, there is nothing to build...
build: off

cache:
  - node_modules -> package.json
