version: 0.1.1.{build}-{branch}

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

hosts:
  localhost: 127.0.0.1

# What combinations to test
environment:
  NODE_ENV: test
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"

platform:
  - x86
#  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build, there is nothing to build...
build: off

matrix:
  allow_failures:
    - nodejs_version: "4"

cache:
  - node_modules -> package.json
